# Generated by Django 5.2.4 on 2025-08-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='upload_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
