# Generated by Django 5.2.5 on 2025-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_paid_user',
            field=models.BooleanField(default=False),
        ),
    ]
